language: node_js
node_js:
  - '10'
  - '11'
  - '12'

script: yarn && yarn build && yarn test

before_install:
  - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc

deploy:
  provider: script
  script: npx lerna publish -y from-git
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
    tags: true
    node: '12'

notifications:
  email:
    recipients:
      - $NPM_EMAIL
    on_success: change
    on_failure: always
